logging:
  level:
    org.springframework.web: "debug"

spring:
  # needed to allow RemoteSpringApplication trigger the
  devtools:
    remote:
      secret: mysecret

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

  datasource:
    url: jdbc:h2:mem:bookstore
    driverClassName: org.h2.Driver
    username: sa
    password: password

#  jackson:
#    serialization:
#      # avoid errors with empty associations
#      fail-on-empty-beans: false